name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  actions: write
  checks: read
  contents: read
  deployments: read
  id-token: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read

jobs:

  build_linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v

  build_macos:
    runs-on: macos-12
    
    steps:
    - uses: actions/checkout@v3
    # - name: List Xcode Versions
    #   run: >
    #     ls -l /Applications | grep "Xcode"
    # - name: Select Xcode
    #   run: >
    #     xcode-select -s /Applications/Xcode_13.4.1.app/Contents/Developer
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.4.1
      with:
        xcode-version: latest-stable
    - name: Build and test
      run: > 
        cd ${{ github.workspace }}/AsyncValueTestApp;
        xcodebuild test -project AsyncValueTestApp.xcodeproj
        -scheme AsyncValueTestApp
        -destination 'platform=iOS Simulator,name=iPhone 13'
        -testPlan AllTests
        -resultBundlePath ${{ runner.temp }}/TestResults.xcresult;
    - name: Test Results
      uses: kishikawakatsumi/xcresulttool@v1.5.0
      if: success() || failure()
      with:
        path: ${{ runner.temp }}/TestResults.xcresult
        token: ${{ secrets.GITHUB_TOKEN }}

    
